"""
Fill missing website UI locale strings from English via DeepL (operator script).

Does NOT call DeepL at React runtime. Run on demand, review output, then commit.

Usage (from repo root):
  python backend/scripts/translate_ui_copy.py --langs nl,fr --dry-run
  python backend/scripts/translate_ui_copy.py --langs nl,fr --apply

Requires DEEPL_AUTH_KEY in backend/.env (Free API: https://api-free.deepl.com).

Writes/updates:
  src/i18n/deeplGeneratedOverrides.ts  (merged in appOverrides via withLocaleExtras)

Skips keys that already have a non-empty value in appOverrides / existing generated file.
Optionally fills missing marketing keys into src/i18n/deeplMarketingGenerated.ts
(manual merge into translations.ts after review).
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
BACKEND = ROOT / "backend"
SCRIPTS = Path(__file__).resolve().parent
EXTRACT = SCRIPTS / "_extract_ts_strings.mjs"
APP_BASE = ROOT / "src" / "i18n" / "appBase.ts"
APP_OVERRIDES = ROOT / "src" / "i18n" / "appOverrides.ts"
GENERATED = ROOT / "src" / "i18n" / "deeplGeneratedOverrides.ts"
TRANSLATIONS = ROOT / "src" / "i18n" / "translations.ts"
MARKETING_GENERATED = ROOT / "src" / "i18n" / "deeplMarketingGenerated.ts"

TARGET_DEFAULT = ["nl", "fr", "ar", "zh", "ru", "es", "it", "de", "ro"]


def _ensure_backend_path() -> None:
    if str(BACKEND) not in sys.path:
        sys.path.insert(0, str(BACKEND))


def _run_extract(file_path: Path, export_name: str) -> dict[str, str]:
    if not EXTRACT.exists():
        raise SystemExit(f"Missing extractor: {EXTRACT}")
    proc = subprocess.run(
        ["node", str(EXTRACT), str(file_path), export_name],
        cwd=str(ROOT),
        capture_output=True,
        text=True,
        check=False,
    )
    if proc.returncode != 0:
        raise SystemExit(f"Extract failed ({export_name}): {proc.stderr or proc.stdout}")
    data = json.loads(proc.stdout or "{}")
    if not isinstance(data, dict):
        raise SystemExit(f"Unexpected extract payload for {export_name}")
    return {str(k): str(v) for k, v in data.items() if isinstance(v, str)}


def _unflatten(flat: dict[str, str]) -> dict:
    root: dict = {}
    for path, value in sorted(flat.items()):
        parts = path.split(".")
        cur = root
        for part in parts[:-1]:
            cur = cur.setdefault(part, {})
        cur[parts[-1]] = value
    return root


def _ts_string(value: str) -> str:
    escaped = (
        value.replace("\\", "\\\\")
        .replace("`", "\\`")
        .replace("${", "\\${")
    )
    # Prefer double quotes when no double-quote inside; else template literal.
    if '"' not in value and "\n" not in value:
        return json.dumps(value, ensure_ascii=False)
    return f"`{escaped}`"


def _emit_object(obj: dict, indent: int = 2) -> str:
    pad = " " * indent
    lines = ["{"]
    items = list(obj.items())
    for i, (key, value) in enumerate(items):
        comma = "," if i < len(items) - 1 else ""
        if isinstance(value, dict):
            nested = _emit_object(value, indent + 2)
            lines.append(f"{pad}{key}: {nested}{comma}")
        else:
            lines.append(f"{pad}{key}: {_ts_string(str(value))}{comma}")
    lines.append((" " * (indent - 2)) + "}")
    return "\n".join(lines)


def _write_generated_overrides(by_lang: dict[str, dict[str, str]]) -> None:
    langs = sorted(by_lang.keys())
    chunks = [
        "/**",
        " * Auto-generated DeepL fills for missing app UI strings.",
        " * Generated by backend/scripts/translate_ui_copy.py — review before commit.",
        " * Merged in appOverrides via withLocaleExtras (does not replace hand-written copy).",
        " */",
        'import type { AppCopy } from "./appBase";',
        'import type { Language } from "./translations";',
        'import type { DeepPartial } from "./mergeDeep";',
        "",
        "export const deeplGeneratedOverrides: Partial<Record<Language, DeepPartial<AppCopy>>> = {",
    ]
    for i, lang in enumerate(langs):
        tree = _unflatten(by_lang[lang])
        body = _emit_object(tree, 4)
        comma = "," if i < len(langs) - 1 else ","
        chunks.append(f"  {lang}: {body}{comma}")
    chunks.append("};")
    chunks.append("")
    GENERATED.write_text("\n".join(chunks), encoding="utf-8")


def _ensure_app_overrides_merge() -> None:
    text = APP_OVERRIDES.read_text(encoding="utf-8")
    if "deeplGeneratedOverrides" in text:
        return
    if 'from "./chatOverrides"' not in text:
        raise SystemExit("Unexpected appOverrides.ts — cannot wire deeplGeneratedOverrides")
    text = text.replace(
        'import { chatOverrides } from "./chatOverrides";\n',
        'import { chatOverrides } from "./chatOverrides";\n'
        'import { deeplGeneratedOverrides } from "./deeplGeneratedOverrides";\n',
        1,
    )
    needle = "  const chat = chatOverrides[locale];\n  if (chat) merged = mergeDeep(merged as AppCopy, chat) as DeepPartial<AppCopy>;\n  return merged;"
    replacement = (
        "  const chat = chatOverrides[locale];\n"
        "  if (chat) merged = mergeDeep(merged as AppCopy, chat) as DeepPartial<AppCopy>;\n"
        "  const deepl = deeplGeneratedOverrides[locale];\n"
        "  if (deepl) merged = mergeDeep(merged as AppCopy, deepl) as DeepPartial<AppCopy>;\n"
        "  return merged;"
    )
    if needle not in text:
        raise SystemExit("Could not find withLocaleExtras merge site in appOverrides.ts")
    APP_OVERRIDES.write_text(text.replace(needle, replacement, 1), encoding="utf-8")
    print(f"Wired deeplGeneratedOverrides into {APP_OVERRIDES.relative_to(ROOT)}")


def _extract_locale_block_flat(file_path: Path, lang: str) -> dict[str, str]:
    """Best-effort: extract `lang: { ... }` top-level block from baseOverrides-style files."""
    # Prefer dedicated export when present.
    if file_path == GENERATED and GENERATED.exists():
        try:
            full = _run_extract(file_path, "deeplGeneratedOverrides")
            # extractor only gets top-level object; for Record<lang, obj> we need nested.
        except SystemExit:
            full = {}
        else:
            # Re-extract as nested via custom: flatten keys are wrong. Parse langs manually below.
            pass

    source = file_path.read_text(encoding="utf-8")
    # Find `  lang: {` at indent 2 inside baseOverrides / generated.
    pattern = re.compile(rf"(?m)^  {re.escape(lang)}: \{{")
    m = pattern.search(source)
    if not m:
        return {}
    start = m.end() - 1  # at '{'
    depth = 0
    i = start
    while i < len(source):
        ch = source[i]
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                block = source[start : i + 1]
                break
        i += 1
    else:
        return {}

    # Write temp snippet as `export const _tmp = <block>` and extract.
    tmp = SCRIPTS / f"_tmp_locale_{lang}.ts"
    try:
        tmp.write_text(f"export const _tmp = {block};\n", encoding="utf-8")
        return _run_extract(tmp, "_tmp")
    finally:
        if tmp.exists():
            tmp.unlink()


def _fill_langs(
    *,
    en_flat: dict[str, str],
    langs: list[str],
    existing_by_lang: dict[str, dict[str, str]],
    translate,
    dry_run: bool,
) -> dict[str, dict[str, str]]:
    result: dict[str, dict[str, str]] = {}
    for lang in langs:
        existing = existing_by_lang.get(lang, {})
        missing = [k for k, v in en_flat.items() if k not in existing or not (existing.get(k) or "").strip()]
        print(f"{lang}: {len(missing)} missing of {len(en_flat)} EN keys")
        filled: dict[str, str] = dict(existing)
        for key in missing:
            src = en_flat[key]
            if dry_run:
                filled[key] = f"[DRY:{lang}] {src}"
                continue
            filled[key] = translate(src, lang)
        # Only keep keys we filled that were missing OR previously generated — store full set of
        # previously existing generated + new fills (not entire hand-written overrides).
        result[lang] = {k: filled[k] for k in missing}
        # Merge prior generated-only keys
        for k, v in existing.items():
            if k not in result[lang]:
                result[lang][k] = v
    return result


def main() -> None:
    parser = argparse.ArgumentParser(description="DeepL-fill missing UI locale overrides from EN")
    parser.add_argument(
        "--langs",
        default=",".join(TARGET_DEFAULT),
        help="Comma-separated target langs (default: all non-en supported)",
    )
    parser.add_argument("--dry-run", action="store_true", help="Do not call DeepL; write placeholder strings")
    parser.add_argument("--apply", action="store_true", help="Write generated override files")
    parser.add_argument(
        "--include-marketing",
        action="store_true",
        help="Also emit deeplMarketingGenerated.ts for missing translations.ts leaves",
    )
    parser.add_argument("--limit", type=int, default=0, help="Max new strings per lang (0 = all)")
    args = parser.parse_args()

    if not args.apply and not args.dry_run:
        raise SystemExit("Pass --dry-run and/or --apply")

    langs = [x.strip().lower() for x in args.langs.split(",") if x.strip()]
    langs = [x for x in langs if x != "en"]
    if not langs:
        raise SystemExit("No target langs")

    _ensure_backend_path()
    from services.deepl_service import deepl_configured, translate_text  # noqa: WPS433

    if args.apply and not args.dry_run and not deepl_configured():
        raise SystemExit("DEEPL_AUTH_KEY is not set in backend/.env")

    def translate(text: str, lang: str) -> str:
        if args.dry_run:
            return text
        return translate_text(text, lang, source_lang="en")

    print("Extracting English appBase...")
    en_flat = _run_extract(APP_BASE, "appEn")
    print(f"  {len(en_flat)} leaf strings")

    existing_by_lang: dict[str, dict[str, str]] = {}
    for lang in langs:
        hand = _extract_locale_block_flat(APP_OVERRIDES, lang)
        gen = _extract_locale_block_flat(GENERATED, lang) if GENERATED.exists() else {}
        # Prefer hand-written: skip translating those keys.
        merged = dict(gen)
        merged.update(hand)
        existing_by_lang[lang] = merged
        print(f"  existing {lang}: {len(hand)} hand + {len(gen)} generated -> {len(merged)} covered")

    # Optional limit for smoke runs: only translate the first N missing keys per lang.
    limit_missing: dict[str, set[str]] = {}
    if args.limit and args.limit > 0:
        for lang in langs:
            missing = [k for k in en_flat if k not in existing_by_lang[lang]]
            limit_missing[lang] = set(missing[: args.limit])
            # Pretend the rest are covered so _fill_langs skips them.
            for k in missing[args.limit :]:
                existing_by_lang[lang][k] = en_flat[k]

    by_lang = _fill_langs(
        en_flat=en_flat,
        langs=langs,
        existing_by_lang=existing_by_lang,
        translate=translate,
        dry_run=args.dry_run and not args.apply,
    )

    # When --apply with dry-run placeholders, still write for structure check.
    if args.apply or args.dry_run:
        # Store only generated fills (keys not in hand-written), so hand copy wins in merge order.
        generated_only: dict[str, dict[str, str]] = {}
        for lang in langs:
            hand = _extract_locale_block_flat(APP_OVERRIDES, lang)
            # Drop EN stubs we injected for --limit, and hand-written keys.
            candidates = {
                k: v
                for k, v in by_lang[lang].items()
                if k not in hand or not (hand.get(k) or "").strip()
            }
            if lang in limit_missing:
                candidates = {k: v for k, v in candidates.items() if k in limit_missing[lang]}
            if not args.dry_run:
                candidates = {
                    k: v
                    for k, v in candidates.items()
                    if v.strip() and v.strip() != (en_flat.get(k) or "").strip()
                }
            generated_only[lang] = candidates
        if args.apply:
            # Preserve prior generated keys for langs not in this run.
            if GENERATED.exists():
                for other in TARGET_DEFAULT:
                    if other in langs:
                        continue
                    prior = _extract_locale_block_flat(GENERATED, other)
                    if prior:
                        generated_only[other] = prior
            _write_generated_overrides(generated_only)
            _ensure_app_overrides_merge()
            print(f"Wrote {GENERATED.relative_to(ROOT)}")
        else:
            total = sum(len(v) for v in generated_only.values())
            print(f"Dry-run only (no write). Would fill {total} generated strings.")

    if args.include_marketing and args.apply:
        print("Extracting marketing translations.en...")
        # translations export is `translations` with nested en/fr/...
        en_m = _extract_locale_block_flat(TRANSLATIONS, "en")
        # The block finder looks for `  en: {` — works inside `export const translations = {`
        marketing_out: dict[str, dict[str, str]] = {}
        for lang in langs:
            have = _extract_locale_block_flat(TRANSLATIONS, lang)
            missing = {k: en_m[k] for k in en_m if k not in have}
            print(f"marketing {lang}: {len(missing)} missing")
            filled = {}
            for k, src in missing.items():
                filled[k] = src if args.dry_run else translate_text(src, lang, source_lang="en")
            marketing_out[lang] = filled
        chunks = [
            "/** Auto-generated marketing DeepL fills — merge into translations.ts after review. */",
            "export const deeplMarketingGenerated = {",
        ]
        for i, lang in enumerate(sorted(marketing_out.keys())):
            tree = _unflatten(marketing_out[lang])
            body = _emit_object(tree, 4)
            chunks.append(f"  {lang}: {body},")
        chunks.append("};")
        chunks.append("")
        MARKETING_GENERATED.write_text("\n".join(chunks), encoding="utf-8")
        print(f"Wrote {MARKETING_GENERATED.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
