"""phase5

Revision ID: 716a50825d63
Revises: 0522fa347498
Create Date: 2026-04-23 13:41:02.631724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '716a50825d63'
down_revision: Union[str, None] = '0522fa347498'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waitlist_entries',
    sa.Column('id', sa.CHAR(length=36, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('user_id', sa.CHAR(length=36, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('mentor_id', sa.CHAR(length=36, collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'mentor_id', name='uq_user_mentor_waitlist')
    )
    op.create_index(op.f('ix_waitlist_entries_mentor_id'), 'waitlist_entries', ['mentor_id'], unique=False)
    op.create_index(op.f('ix_waitlist_entries_user_id'), 'waitlist_entries', ['user_id'], unique=False)
    
    op.add_column('bookings', sa.Column('reschedule_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('bookings', sa.Column('reminder_24h_sent', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('bookings', sa.Column('reminder_1h_sent', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('bookings', sa.Column('reminder_15m_sent', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('bookings', sa.Column('no_show_by', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'no_show_by')
    op.drop_column('bookings', 'reminder_15m_sent')
    op.drop_column('bookings', 'reminder_1h_sent')
    op.drop_column('bookings', 'reminder_24h_sent')
    op.drop_column('bookings', 'reschedule_count')
    
    op.drop_index(op.f('ix_waitlist_entries_user_id'), table_name='waitlist_entries')
    op.drop_index(op.f('ix_waitlist_entries_mentor_id'), table_name='waitlist_entries')
    op.drop_table('waitlist_entries')
    # ### end Alembic commands ###
